### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by am1tyadav** [TheSoundOfAIOSR/rg_text_to_sound#37]
I just tried the end to end pipeline from project_common with the latest changes on dev. It is working well for me. The only problem I have now is when there is a speech input without any keywords (eg. i said "nasal") which returns an empty list and we get division by zero in tts:` ZeroDivisionError: float division by zero`

**Comment by Mirco-Nani** [comment]
I tried to reproduce the error both on the tts repository and on the end to end pipeline from project_common.
I wasn't able to reproduce the error after many trials.
I spoke to Amit and we agreed to close this issue for now, if the problem comes back, the issue will be re-opened with more details on how to reproduce it
